export enum HttpStatusCode {
  OK = 200,
  CREATED,
  ACCEPTED,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED,
  PAYMENT_REQUIRED,
  FORBIDDEN,
  NOT_FOUND,
  INTERNAL_ERROR = 500,
  SERVICE_UNAVAILABLE = 503
}
