export const enum STOREKEY {
  LANGUAGE = 'lang',
  THEME = 'theme',
  NAV_THEME = 'default',
  FONT_SIZE = 'size',
  TEXT_DIR = 'dir',
  USER_TOKEN = 'token',
  ID_EMPRESA = 'id_empresa',
  ID_SUCURSAL = 'id_sucursal',
  USER_ID = 'user_id',
  USER_LOGIN_EXPIRE = 'login_expire',
  USER_EXPIRE = 'expire',
  MODULE_ID = 'moduleId',
  CURRENT_MODULE = 'module',
  SESSIONID = 'sessid',
  TIPOAUT = 'idtipoaut',
  VERIFY = 'verificado',
  EMPRESA = 'idempresa',
  SUCURSAL = 'idesucursal',
  DECIMAL = 'decimal',
  FORMATDATE = 'format_date',
  MODULOS = 'modulos',
  MODULOS_PATH = 'modulos_path',
  // ----
  DEFAULT_PROJECT = 'proyecto',
  HIDDEN = 'hidden',

  PRIVIGELES = 'privileges',
  DEBUG = 'debug',
  OFFLINE = 'offline',
}

