
export const COUNTRY_LIST = [
  { value: 'AF', name: 'Afghanistan' },
  { value: 'AX', name: 'Åland Islands' },
  { value: 'AL', name: 'Albania' },
  { value: 'DZ', name: 'Algeria' },
  { value: 'AS', name: 'American Samoa' },
  { value: 'AD', name: 'Andorra' },
  { value: 'AO', name: 'Angola' },
  { value: 'AI', name: 'Anguilla' },
  { value: 'AQ', name: 'Antarctica' },
  { value: 'AG', name: 'Antigua and Barbuda' },
  { value: 'AR', name: 'Argentina' },
  { value: 'AM', name: 'Armenia' },
  { value: 'AW', name: 'Aruba' },
  { value: 'AU', name: 'Australia' },
  { value: 'AT', name: 'Austria' },
  { value: 'AZ', name: 'Azerbaijan' },
  { value: 'BS', name: 'Bahamas' },
  { value: 'BH', name: 'Bahrain' },
  { value: 'BD', name: 'Bangladesh' },
  { value: 'BB', name: 'Barbados' },
  { value: 'BY', name: 'Belarus' },
  { value: 'BE', name: 'Belgium' },
  { value: 'BZ', name: 'Belize' },
  { value: 'BJ', name: 'Benin' },
  { value: 'BM', name: 'Bermuda' },
  { value: 'BT', name: 'Bhutan' },
  { value: 'BO', name: 'Bolivia, Plurinational State of' },
  { value: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'BA', name: 'Bosnia and Herzegovina' },
  { value: 'BW', name: 'Botswana' },
  { value: 'BV', name: 'Bouvet Island' },
  { value: 'BR', name: 'Brazil' },
  { value: 'IO', name: 'British Indian Ocean Territory' },
  { value: 'BN', name: 'Brunei Darussalam' },
  { value: 'BG', name: 'Bulgaria' },
  { value: 'BF', name: 'Burkina Faso' },
  { value: 'BI', name: 'Burundi' },
  { value: 'KH', name: 'Cambodia' },
  { value: 'CM', name: 'Cameroon' },
  { value: 'CA', name: 'Canada' },
  { value: 'CV', name: 'Cape Verde' },
  { value: 'KY', name: 'Cayman Islands' },
  { value: 'CF', name: 'Central African Republic' },
  { value: 'TD', name: 'Chad' },
  { value: 'CL', name: 'Chile' },
  { value: 'CN', name: 'China' },
  { value: 'CX', name: 'Christmas Island' },
  { value: 'CC', name: 'Cocos (Keeling) Islands' },
  { value: 'CO', name: 'Colombia' },
  { value: 'KM', name: 'Comoros' },
  { value: 'CG', name: 'Congo' },
  { value: 'CD', name: 'Congo, the Democratic Republic of the' },
  { value: 'CK', name: 'Cook Islands' },
  { value: 'CR', name: 'Costa Rica' },
  { value: 'CI', name: 'Côte d\'Ivoire' },
  { value: 'HR', name: 'Croatia' },
  { value: 'CU', name: 'Cuba' },
  { value: 'CW', name: 'Curaçao' },
  { value: 'CY', name: 'Cyprus' },
  { value: 'CZ', name: 'Czech Republic' },
  { value: 'DK', name: 'Denmark' },
  { value: 'DJ', name: 'Djibouti' },
  { value: 'DM', name: 'Dominica' },
  { value: 'DO', name: 'Dominican Republic' },
  { value: 'EC', name: 'Ecuador' },
  { value: 'EG', name: 'Egypt' },
  { value: 'SV', name: 'El Salvador' },
  { value: 'GQ', name: 'Equatorial Guinea' },
  { value: 'ER', name: 'Eritrea' },
  { value: 'EE', name: 'Estonia' },
  { value: 'ET', name: 'Ethiopia' },
  { value: 'FK', name: 'Falkland Islands (Malvinas)' },
  { value: 'FO', name: 'Faroe Islands' },
  { value: 'FJ', name: 'Fiji' },
  { value: 'FI', name: 'Finland' },
  { value: 'FR', name: 'France' },
  { value: 'GF', name: 'French Guiana' },
  { value: 'PF', name: 'French Polynesia' },
  { value: 'TF', name: 'French Southern Territories' },
  { value: 'GA', name: 'Gabon' },
  { value: 'GM', name: 'Gambia' },
  { value: 'GE', name: 'Georgia' },
  { value: 'DE', name: 'Germany' },
  { value: 'GH', name: 'Ghana' },
  { value: 'GI', name: 'Gibraltar' },
  { value: 'GR', name: 'Greece' },
  { value: 'GL', name: 'Greenland' },
  { value: 'GD', name: 'Grenada' },
  { value: 'GP', name: 'Guadeloupe' },
  { value: 'GU', name: 'Guam' },
  { value: 'GT', name: 'Guatemala' },
  { value: 'GG', name: 'Guernsey' },
  { value: 'GN', name: 'Guinea' },
  { value: 'GW', name: 'Guinea-Bissau' },
  { value: 'GY', name: 'Guyana' },
  { value: 'HT', name: 'Haiti' },
  { value: 'HM', name: 'Heard Island and McDonald Islands' },
  { value: 'VA', name: 'Holy See (Vatican City State)' },
  { value: 'HN', name: 'Honduras' },
  { value: 'HK', name: 'Hong Kong' },
  { value: 'HU', name: 'Hungary' },
  { value: 'IS', name: 'Iceland' },
  { value: 'IN', name: 'India' },
  { value: 'ID', name: 'Indonesia' },
  { value: 'IR', name: 'Iran, Islamic Republic of' },
  { value: 'IQ', name: 'Iraq' },
  { value: 'IE', name: 'Ireland' },
  { value: 'IM', name: 'Isle of Man' },
  { value: 'IL', name: 'Israel' },
  { value: 'IT', name: 'Italy' },
  { value: 'JM', name: 'Jamaica' },
  { value: 'JP', name: 'Japan' },
  { value: 'JE', name: 'Jersey' },
  { value: 'JO', name: 'Jordan' },
  { value: 'KZ', name: 'Kazakhstan' },
  { value: 'KE', name: 'Kenya' },
  { value: 'KI', name: 'Kiribati' },
  { value: 'KP', name: 'Korea, Democratic People\'s Republic of' },
  { value: 'KR', name: 'Korea, Republic of' },
  { value: 'KW', name: 'Kuwait' },
  { value: 'KG', name: 'Kyrgyzstan' },
  { value: 'LA', name: 'Lao People\'s Democratic Republic' },
  { value: 'LV', name: 'Latvia' },
  { value: 'LB', name: 'Lebanon' },
  { value: 'LS', name: 'Lesotho' },
  { value: 'LR', name: 'Liberia' },
  { value: 'LY', name: 'Libya' },
  { value: 'LI', name: 'Liechtenstein' },
  { value: 'LT', name: 'Lithuania' },
  { value: 'LU', name: 'Luxembourg' },
  { value: 'MO', name: 'Macao' },
  { value: 'MK', name: 'Macedonia, the former Yugoslav Republic of' },
  { value: 'MG', name: 'Madagascar' },
  { value: 'MW', name: 'Malawi' },
  { value: 'MY', name: 'Malaysia' },
  { value: 'MV', name: 'Maldives' },
  { value: 'ML', name: 'Mali' },
  { value: 'MT', name: 'Malta' },
  { value: 'MH', name: 'Marshall Islands' },
  { value: 'MQ', name: 'Martinique' },
  { value: 'MR', name: 'Mauritania' },
  { value: 'MU', name: 'Mauritius' },
  { value: 'YT', name: 'Mayotte' },
  { value: 'MX', name: 'Mexico' },
  { value: 'FM', name: 'Micronesia, Federated States of' },
  { value: 'MD', name: 'Moldova, Republic of' },
  { value: 'MC', name: 'Monaco' },
  { value: 'MN', name: 'Mongolia' },
  { value: 'ME', name: 'Montenegro' },
  { value: 'MS', name: 'Montserrat' },
  { value: 'MA', name: 'Morocco' },
  { value: 'MZ', name: 'Mozambique' },
  { value: 'MM', name: 'Myanmar' },
  { value: 'NA', name: 'Namibia' },
  { value: 'NR', name: 'Nauru' },
  { value: 'NP', name: 'Nepal' },
  { value: 'NL', name: 'Netherlands' },
  { value: 'NC', name: 'New Caledonia' },
  { value: 'NZ', name: 'New Zealand' },
  { value: 'NI', name: 'Nicaragua' },
  { value: 'NE', name: 'Niger' },
  { value: 'NG', name: 'Nigeria' },
  { value: 'NU', name: 'Niue' },
  { value: 'NF', name: 'Norfolk Island' },
  { value: 'MP', name: 'Northern Mariana Islands' },
  { value: 'NO', name: 'Norway' },
  { value: 'OM', name: 'Oman' },
  { value: 'PK', name: 'Pakistan' },
  { value: 'PW', name: 'Palau' },
  { value: 'PS', name: 'Palestinian Territory, Occupied' },
  { value: 'PA', name: 'Panama' },
  { value: 'PG', name: 'Papua New Guinea' },
  { value: 'PY', name: 'Paraguay' },
  { value: 'PE', name: 'Peru' },
  { value: 'PH', name: 'Philippines' },
  { value: 'PN', name: 'Pitcairn' },
  { value: 'PL', name: 'Poland' },
  { value: 'PT', name: 'Portugal' },
  { value: 'PR', name: 'Puerto Rico' },
  { value: 'QA', name: 'Qatar' },
  { value: 'RE', name: 'Réunion' },
  { value: 'RO', name: 'Romania' },
  { value: 'RU', name: 'Russian Federation' },
  { value: 'RW', name: 'Rwanda' },
  { value: 'BL', name: 'Saint Barthélemy' },
  { value: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { value: 'KN', name: 'Saint Kitts and Nevis' },
  { value: 'LC', name: 'Saint Lucia' },
  { value: 'MF', name: 'Saint Martin (French part)' },
  { value: 'PM', name: 'Saint Pierre and Miquelon' },
  { value: 'VC', name: 'Saint Vincent and the Grenadines' },
  { value: 'WS', name: 'Samoa' },
  { value: 'SM', name: 'San Marino' },
  { value: 'ST', name: 'Sao Tome and Principe' },
  { value: 'SA', name: 'Saudi Arabia' },
  { value: 'SN', name: 'Senegal' },
  { value: 'RS', name: 'Serbia' },
  { value: 'SC', name: 'Seychelles' },
  { value: 'SL', name: 'Sierra Leone' },
  { value: 'SG', name: 'Singapore' },
  { value: 'SX', name: 'Sint Maarten (Dutch part)' },
  { value: 'SK', name: 'Slovakia' },
  { value: 'SI', name: 'Slovenia' },
  { value: 'SB', name: 'Solomon Islands' },
  { value: 'SO', name: 'Somalia' },
  { value: 'ZA', name: 'South Africa' },
  { value: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  { value: 'SS', name: 'South Sudan' },
  { value: 'ES', name: 'Spain' },
  { value: 'LK', name: 'Sri Lanka' },
  { value: 'SD', name: 'Sudan' },
  { value: 'SR', name: 'Suriname' },
  { value: 'SJ', name: 'Svalbard and Jan Mayen' },
  { value: 'SZ', name: 'Swaziland' },
  { value: 'SE', name: 'Sweden' },
  { value: 'CH', name: 'Switzerland' },
  { value: 'SY', name: 'Syrian Arab Republic' },
  { value: 'TW', name: 'Taiwan, Province of China' },
  { value: 'TJ', name: 'Tajikistan' },
  { value: 'TZ', name: 'Tanzania, United Republic of' },
  { value: 'TH', name: 'Thailand' },
  { value: 'TL', name: 'Timor-Leste' },
  { value: 'TG', name: 'Togo' },
  { value: 'TK', name: 'Tokelau' },
  { value: 'TO', name: 'Tonga' },
  { value: 'TT', name: 'Trinidad and Tobago' },
  { value: 'TN', name: 'Tunisia' },
  { value: 'TR', name: 'Turkey' },
  { value: 'TM', name: 'Turkmenistan' },
  { value: 'TC', name: 'Turks and Caicos Islands' },
  { value: 'TV', name: 'Tuvalu' },
  { value: 'UG', name: 'Uganda' },
  { value: 'UA', name: 'Ukraine' },
  { value: 'AE', name: 'United Arab Emirates' },
  { value: 'GB', name: 'United Kingdom' },
  { value: 'US', name: 'United States' },
  { value: 'UM', name: 'United States Minor Outlying Islands' },
  { value: 'UY', name: 'Uruguay' },
  { value: 'UZ', name: 'Uzbekistan' },
  { value: 'VU', name: 'Vanuatu' },
  { value: 'VE', name: 'Venezuela, Bolivarian Republic of' },
  { value: 'VN', name: 'Viet Nam' },
  { value: 'VG', name: 'Virgin Islands, British' },
  { value: 'VI', name: 'Virgin Islands, U.S.' },
  { value: 'WF', name: 'Wallis and Futuna' },
  { value: 'EH', name: 'Western Sahara' },
  { value: 'YE', name: 'Yemen' },
  { value: 'ZM', name: 'Zambia' },
  { value: 'ZW', name: 'Zimbabwe' },
];



export const TIMEZONE_LIST = [
  { value: '1', name: 'International Date Line West (GMT-12:00)' },
  { value: '2', name: 'Midway Island, Samoa (GMT-11:00)' },
  { value: '3', name: 'Hawaii (GMT-10:00)' },
  { value: '4', name: 'Alaska (GMT-09:00)' },
  { value: '5', name: 'Pacific Time (US & Canada) (GMT-08:00)' },
  { value: '6', name: 'Tijuana, Baja California (GMT-08:00)' },
  { value: '7', name: 'Arizona (GMT-07:00)' },
  { value: '8', name: 'Chihuahua, La Paz, Mazatlan (GMT-07:00)' },
  { value: '9', name: 'Mountain Time (US & Canada) (GMT-07:00)' },
  { value: '10', name: 'Central America (GMT-06:00)' },
  { value: '11', name: 'Central Time (US & Canada) (GMT-06:00)' },
  { value: '12', name: 'Guadalajara, Mexico City, Monterrey (GMT-06:00)' },
  { value: '13', name: 'Saskatchewan (GMT-06:00)' },
  { value: '14', name: 'Bogota, Lima, Quito, Rio Branco (GMT-05:00)' },
  { value: '15', name: 'Eastern Time (US & Canada) (GMT-05:00)' },
  { value: '16', name: 'Indiana (East) (GMT-05:00)' },
  { value: '17', name: 'Atlantic Time (Canada) (GMT-04:00)' },
  { value: '18', name: 'Caracas, La Paz (GMT-04:00)' },
  { value: '19', name: 'Manaus (GMT-04:00)' },
  { value: '20', name: 'Santiago (GMT-04:00)' },
  { value: '21', name: 'Newfoundland (GMT-03:30)' },
  { value: '22', name: 'Brasilia (GMT-03:00)' },
  { value: '23', name: 'Buenos Aires, Georgetown (GMT-03:00)' },
  { value: '24', name: 'Greenland (GMT-03:00)' },
  { value: '25', name: 'Montevideo (GMT-03:00)' },
  { value: '26', name: 'Mid-Atlantic (GMT-02:00)' },
  { value: '27', name: 'Cape Verde Is. (GMT-01:00)' },
  { value: '28', name: 'Azores (GMT-01:00)' },
  { value: '29', name: 'Casablanca, Monrovia, Reykjavik (GMT+00:00)' },
  { value: '30', name: 'Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London (GMT+00:00)' },
  { value: '31', name: 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna (GMT+01:00)' },
  { value: '32', name: 'Belgrade, Bratislava, Budapest, Ljubljana, Prague (GMT+01:00)' },
  { value: '33', name: 'Brussels, Copenhagen, Madrid, Paris (GMT+01:00)' },
  { value: '34', name: 'Sarajevo, Skopje, Warsaw, Zagreb (GMT+01:00)' },
  { value: '35', name: 'West Central Africa (GMT+01:00)' },
  { value: '36', name: 'Amman (GMT+02:00)' },
  { value: '37', name: 'Athens, Bucharest, Istanbul (GMT+02:00)' },
  { value: '38', name: 'Beirut (GMT+02:00)' },
  { value: '39', name: 'Cairo (GMT+02:00)' },
  { value: '40', name: 'Harare, Pretoria (GMT+02:00)' },
  { value: '41', name: 'Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius (GMT+02:00)' },
  { value: '42', name: 'Jerusalem (GMT+02:00)' },
  { value: '43', name: 'Minsk (GMT+02:00)' },
  { value: '44', name: 'Windhoek (GMT+02:00)' },
  { value: '45', name: 'Kuwait, Riyadh, Baghdad (GMT+03:00)' },
  { value: '46', name: 'Moscow, St. Petersburg, Volgograd (GMT+03:00)' },
  { value: '47', name: 'Nairobi (GMT+03:00)' },
  { value: '48', name: 'Tbilisi (GMT+03:00)' },
  { value: '49', name: 'Tehran (GMT+03:30)' },
  { value: '50', name: 'Abu Dhabi, Muscat (GMT+04:00)' },
  { value: '51', name: 'Baku (GMT+04:00)' },
  { value: '52', name: 'Yerevan (GMT+04:00)' },
  { value: '53', name: 'Kabul (GMT+04:30)' },
  { value: '54', name: 'Yekaterinburg (GMT+05:00)' },
  { value: '55', name: 'Islamabad, Karachi, Tashkent (GMT+05:00)' },
  { value: '56', name: 'Sri Jayawardenapura (GMT+05:30)' },
  { value: '57', name: 'Chennai, Kolkata, Mumbai, New Delhi (GMT+05:30)' },
  { value: '58', name: 'Kathmandu (GMT+05:45)' },
  { value: '59', name: 'Almaty, Novosibirsk (GMT+06:00)' },
  { value: '60', name: 'Astana, Dhaka (GMT+06:00)' },
  { value: '61', name: 'Yangon (Rangoon) (GMT+06:30)' },
  { value: '62', name: 'Bangkok, Hanoi, Jakarta (GMT+07:00)' },
  { value: '63', name: 'Krasnoyarsk (GMT+07:00)' },
  { value: '64', name: 'Beijing, Chongqing, Hong Kong, Urumqi (GMT+08:00)' },
  { value: '65', name: 'Kuala Lumpur, Singapore (GMT+08:00)' },
  { value: '66', name: 'Irkutsk, Ulaan Bataar (GMT+08:00)' },
  { value: '67', name: 'Perth (GMT+08:00)' },
  { value: '68', name: 'Taipei (GMT+08:00)' },
  { value: '69', name: 'Osaka, Sapporo, Tokyo (GMT+09:00)' },
  { value: '70', name: 'Seoul (GMT+09:00)' },
  { value: '71', name: 'Yakutsk (GMT+09:00)' },
  { value: '72', name: 'Adelaide (GMT+09:30)' },
  { value: '73', name: 'Darwin (GMT+09:30)' },
  { value: '74', name: 'Brisbane (GMT+10:00)' },
  { value: '75', name: 'Canberra, Melbourne, Sydney (GMT+10:00)' },
  { value: '76', name: 'Hobart (GMT+10:00)' },
  { value: '77', name: 'Guam, Port Moresby (GMT+10:00)' },
  { value: '78', name: 'Vladivostok (GMT+10:00)' },
  { value: '79', name: 'Magadan, Solomon Is., New Caledonia (GMT+11:00)' },
  { value: '80', name: 'Auckland, Wellington (GMT+12:00)' },
  { value: '81', name: 'Fiji, Kamchatka, Marshall Is. (GMT+12:00)' },
  { value: '82', name: 'Nuku\'alofa (GMT+ 13: 00)' },
];


export const CURRENCY_LIST = [
  { value: 'USD', name: 'America (United States) Dollars' },
  { value: 'AFN', name: 'Afghanistan Afghanis' },
  { value: 'ALL', name: 'Albania Leke' },
  { value: 'DZD', name: 'Algeria Dinars' },
  { value: 'ARS', name: 'Argentina Pesos' },
  { value: 'AUD', name: 'Australia Dollars' },
  { value: 'ATS', name: 'Austria Schillings' },

  { value: 'BSD', name: 'Bahamas Dollars' },
  { value: 'BHD', name: 'Bahrain Dinars' },
  { value: 'BDT', name: 'Bangladesh Taka' },
  { value: 'BBD', name: 'Barbados Dollars' },
  { value: 'BEF', name: 'Belgium Francs' },
  { value: 'BMD', name: 'Bermuda Dollars' },

  { value: 'BRL', name: 'Brazil Reais' },
  { value: 'BGN', name: 'Bulgaria Leva' },
  { value: 'CAD', name: 'Canada Dollars' },
  { value: 'XOF', name: 'CFA BCEAO Francs' },
  { value: 'XAF', name: 'CFA BEAC Francs' },
  { value: 'CLP', name: 'Chile Pesos' },

  { value: 'CNY', name: 'China Yuan Renminbi' },
  { value: 'CNY', name: 'RMB (China Yuan Renminbi)' },
  { value: 'COP', name: 'Colombia Pesos' },
  { value: 'XPF', name: 'CFP Francs' },
  { value: 'CRC', name: 'Costa Rica Colones' },
  { value: 'HRK', name: 'Croatia Kuna' },

  { value: 'CYP', name: 'Cyprus Pounds' },
  { value: 'CZK', name: 'Czech Republic Koruny' },
  { value: 'DKK', name: 'Denmark Kroner' },
  { value: 'DEM', name: 'Deutsche (Germany) Marks' },
  { value: 'DOP', name: 'Dominican Republic Pesos' },
  { value: 'NLG', name: 'Dutch (Netherlands) Guilders' },

  { value: 'XCD', name: 'Eastern Caribbean Dollars' },
  { value: 'EGP', name: 'Egypt Pounds' },
  { value: 'EEK', name: 'Estonia Krooni' },
  { value: 'EUR', name: 'Euro' },
  { value: 'FJD', name: 'Fiji Dollars' },
  { value: 'FIM', name: 'Finland Markkaa' },

  { value: 'FRF', name: 'France Francs' },
  { value: 'DEM', name: 'Germany Deutsche Marks' },
  { value: 'XAU', name: 'Gold Ounces' },
  { value: 'GRD', name: 'Greece Drachmae' },
  { value: 'GTQ', name: 'Guatemalan Quetzal' },
  { value: 'NLG', name: 'Holland (Netherlands) Guilders' },
  { value: 'HKD', name: 'Hong Kong Dollars' },

  { value: 'HUF', name: 'Hungary Forint' },
  { value: 'ISK', name: 'Iceland Kronur' },
  { value: 'XDR', name: 'IMF Special Drawing Right' },
  { value: 'INR', name: 'India Rupees' },
  { value: 'IDR', name: 'Indonesia Rupiahs' },
  { value: 'IRR', name: 'Iran Rials' },

  { value: 'IQD', name: 'Iraq Dinars' },
  { value: 'IEP', name: 'Ireland Pounds' },
  { value: 'ILS', name: 'Israel New Shekels' },
  { value: 'ITL', name: 'Italy Lire' },
  { value: 'JMD', name: 'Jamaica Dollars' },
  { value: 'JPY', name: 'Japan Yen' },
  { value: 'JOD', name: 'Jordan Dinars' },
  { value: 'KES', name: 'Kenya Shillings' },
  { value: 'KRW', name: 'Korea (South) Won' },
  { value: 'KWD', name: 'Kuwait Dinars' },
  { value: 'LBP', name: 'Lebanon Pounds' },
  { value: 'LUF', name: 'Luxembourg Francs' },

  { value: 'MYR', name: 'Malaysia Ringgits' },
  { value: 'MTL', name: 'Malta Liri' },
  { value: 'MUR', name: 'Mauritius Rupees' },
  { value: 'MXN', name: 'Mexico Pesos' },
  { value: 'MAD', name: 'Morocco Dirhams' },
  { value: 'NLG', name: 'Netherlands Guilders' },

  { value: 'NZD', name: 'New Zealand Dollars' },
  { value: 'NOK', name: 'Norway Kroner' },
  { value: 'OMR', name: 'Oman Rials' },
  { value: 'PKR', name: 'Pakistan Rupees' },
  { value: 'XPD', name: 'Palladium Ounces' },
  { value: 'PEN', name: 'Peru Nuevos Soles' },

  { value: 'PHP', name: 'Philippines Pesos' },
  { value: 'XPT', name: 'Platinum Ounces' },
  { value: 'PLN', name: 'Poland Zlotych' },
  { value: 'PTE', name: 'Portugal Escudos' },
  { value: 'QAR', name: 'Qatar Riyals' },
  { value: 'RON', name: 'Romania New Lei' },

  { value: 'ROL', name: 'Romania Lei' },
  { value: 'RUB', name: 'Russia Rubles' },
  { value: 'SAR', name: 'Saudi Arabia Riyals' },
  { value: 'XAG', name: 'Silver Ounces' },
  { value: 'SGD', name: 'Singapore Dollars' },
  { value: 'SKK', name: 'Slovakia Koruny' },

  { value: 'SIT', name: 'Slovenia Tolars' },
  { value: 'ZAR', name: 'South Africa Rand' },
  { value: 'KRW', name: 'South Korea Won' },
  { value: 'ESP', name: 'Spain Pesetas' },
  { value: 'XDR', name: 'Special Drawing Rights (IMF)' },
  { value: 'LKR', name: 'Sri Lanka Rupees' },

  { value: 'SDD', name: 'Sudan Dinars' },
  { value: 'SEK', name: 'Sweden Kronor' },
  { value: 'CHF', name: 'Switzerland Francs' },
  { value: 'TWD', name: 'Taiwan New Dollars' },
  { value: 'THB', name: 'Thailand Baht' },
  { value: 'TTD', name: 'Trinidad and Tobago Dollars' },

  { value: 'TND', name: 'Tunisia Dinars' },
  { value: 'TRY', name: 'Turkey New Lira' },
  { value: 'AED', name: 'United Arab Emirates Dirhams' },
  { value: 'GBP', name: 'United Kingdom Pounds' },
  { value: 'USD', name: 'United States Dollars' },
  { value: 'VEB', name: 'Venezuela Bolivares' },

  { value: 'VND', name: 'Vietnam Dong' },
  { value: 'ZMK', name: 'Zambia Kwacha' },
];
